using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Singleton<T> : MonoBehaviour where T : Singleton<T>
{
    public static T Instance;

    protected virtual void Awake()
    {
        if (Instance == null)
        {
            Instance = this as T;
            InitAwake();
        }
        else if (Instance != this)
        {
            Destroy(this.gameObject);
        }
    }

    public virtual void InitAwake()
    {
        if (Input.multiTouchEnabled) Input.multiTouchEnabled = false;
        Application.targetFrameRate = 0;
    }

    private void OnDestroy()
    {
        if (Instance == this)
        {
            Instance = null;
        }
    }
}